properly handle subscribed topics with + wildcard
adrianromero/helloiot pull request #3
Opened 2019-10-08 15:53 UTC by cjaikaeo

Currently subscribe panels can handle wildcard topics containing # properly, but not topics containing +. This pull request contains a fix that allows a subscribe panel with + as part of the topic name to correctly receive incoming messages by employing a topic matching function available in Paho's MQTT implementation.

2019-10-08 20:22 UTC, adrianromero requested changes
Thanks for the fix. I have to keep Java 8 sources compatibility due to the mobile (Android) version. Please replace 'var' by 'Entry<String, List<TopicSubscription>>' before approving the pull request.

2019-10-09 03:44 UTC, cjaikaeo commented
I already replaced `var` with `Map.Entry<String, List<TopicSubscription>>`.  However, gradle complained about org.openjfx.javafxplugin class not compatible with Java 8, so I couldn't verify the code against Java 8.  (The code compiled with Java 13 though.)

2019-10-11 14:55 UTC, merged

2019-10-11 15:04 UTC, adrianromero commented
Merged! 

As you can see it is needed to merge your changes into the branch mobile to make the gradle script work for Android and Java 8. I have two different gradle build files. One for desktop and java 11 in the master branch and other for android and java 8 in the branch mobile. Maybe I should create one single gradle build file for both environments.

Thanks

2019-10-12 02:16 UTC, cjaikaeo commented
Thank you so much for accepting the PR, and for creating such wonderful work.